classDiagram
    Student "1" <--> "0..*" ClubMembership : has membership
    ClubMembership "0..*" --> "1" StudentClub : associatedWith
    StudentClub "1" --> "0..*" Event : organizes
    Event "1" -- "0..*" RSVP : has
    Student "1" --> "0..*" RSVP : submits
    StudentClub "1" --> "0..*" FundingApplication : submits
    FacultyAdministrator "1" --> "0..*" FundingApplication : reviews

    class Student {
        int stuId
        String name
        String email
    %%        viewEvents()
    %%        rsvpEvent(eventId)
    %%        cancelRSVP(eventId)
    }

    class ClubMembership {
        int stuId
        int clubId
        boolean isAdministrator
        Date joinDate
    }

    class StudentClub {
        int clubId
        String name
        String description
    %%        createEvent(title, description, venue, capacity)
    %%        editEvent(eventId, title, description, venue, capacity)
    %%        cancelEvent(eventId)
    %%        manageAdministrators(studentId, action)
    %%        viewFundingApplications()
    }

    class Event {
        int id
        String title
        String description
        int capacity
        String venue
        Date date
        String status
    %%        createRSVP(studentId)
    %%        editRSVP(rsvpId, newDetails)
    %%        cancelRSVP(rsvpId)
    %%        cancelEvent()
    }

    class RSVP {
        int id
        Date date
        String status
    }

    class FundingApplication {
        int id
        String description
        float amountRequested
        String status
    %%        createApplication(description, amountRequested)
    %%        editApplication(applicationId, newDetails)
    %%        cancelApplication(applicationId)
    %%        viewApplicationStatus()
    }

    class FacultyAdministrator {
        int id
        String name
        String email
    %%        approveApplication(applicationId)
    %%        rejectApplication(applicationId)
    %%        viewAllApplications()
    }